# Generated by Django 2.2.2 on 2019-06-15 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, verbose_name=models.Model)),
                ('name', models.CharField(max_length=200, verbose_name=models.Model)),
                ('parent_slug', models.CharField(max_length=200, verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orig_code', models.CharField(max_length=5, verbose_name=models.Model)),
                ('dest_code', models.CharField(max_length=5, verbose_name=models.Model)),
                ('day', models.DateField(verbose_name=models.Model)),
                ('price', models.IntegerField(default=0, verbose_name=models.Model)),
            ],
        ),
        migrations.CreateModel(
            name='Regions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(max_length=200, verbose_name=models.Model)),
                ('name', models.CharField(max_length=200, verbose_name=models.Model)),
                ('parent_slug', models.CharField(max_length=200, verbose_name=models.Model)),
            ],
        ),
    ]
