# Generated by Django 2.2.2 on 2019-06-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='dd',
            fields=[
                ('orig_code', models.CharField(max_length=200, primary_key=True, serialize=False, verbose_name=models.Model)),
                ('dest_code', models.CharField(max_length=200, verbose_name=models.Model)),
                ('day', models.DateField(max_length=200, verbose_name=models.Model)),
                ('price', models.FloatField(max_length=200, verbose_name=models.Model)),
            ],
        ),
    ]
