# Generated by Django 2.2.2 on 2019-06-15 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='dest_code',
            field=models.TextField(max_length=5, verbose_name=models.Model),
        ),
        migrations.AlterField(
            model_name='prices',
            name='orig_code',
            field=models.TextField(max_length=5, verbose_name=models.Model),
        ),
    ]
