# Generated by Django 2.2.2 on 2019-06-10 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_dd'),
    ]

    operations = [
        migrations.DeleteModel(
            name='dd',
        ),
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(max_length=200, verbose_name=models.Model),
        ),
    ]
