# Generated by Django 2.2.2 on 2019-06-10 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190610_1657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(verbose_name=models.Model),
        ),
    ]
